apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: azure-quiz
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflare-token
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: micro-army/cloudflare-api-token
