import type { EnvironmentDef } from './types';

export const overview: EnvironmentDef = {
  label: '🌐 Full Overview',
  cameraPos: [0, -1400, 1000],
  cameraTarget: [0, 0, 155],
  layers: [
    { id: 'cloudflare', label: '☁️ Cloudflare', z: 300, w: 2000, h: 140 },
    { id: 'public-sites', label: '🌐 Public Sites', z: 220, w: 2000, h: 130 },
    { id: 'services', label: '⚙️ Services', z: 140, w: 2200, h: 300 },
    { id: 'external', label: '☁️ External / SaaS', z: 30, w: 2000, h: 140 },
  ],
  nodes: [
    // Cloudflare
    { id: 'dns', layer: 'cloudflare', label: 'DNS', subtitle: 'Cloudflare DNS', x: -700, z: 300, w: 200, h: 60, cat: 'infrastructure', desc: 'DNS resolution via Cloudflare.', url: '' },
    { id: 'tunnel', layer: 'cloudflare', label: 'Tunnel', subtitle: 'Cloudflare Tunnel', x: -200, z: 300, w: 200, h: 60, cat: 'infrastructure', desc: 'Secure tunnel to k3s cluster.', url: '' },
    { id: 'ssl', layer: 'cloudflare', label: 'SSL/TLS', subtitle: 'Edge Termination', x: 300, z: 300, w: 200, h: 60, cat: 'infrastructure', desc: 'SSL termination at Cloudflare edge.', url: '' },
    // Public Sites
    { id: 'site-main', layer: 'public-sites', label: 'completeautomate.com', subtitle: 'Main Website', x: -800, z: 220, w: 220, h: 60, cat: 'site', desc: 'Public marketing website.', url: 'https://completeautomate.com' },
    { id: 'site-admin', layer: 'public-sites', label: 'admin.completeautomate.com', subtitle: 'Helios Dashboard', x: -450, z: 220, w: 220, h: 60, cat: 'site', desc: 'Admin dashboard for lead management.', url: 'https://admin.completeautomate.com' },
    { id: 'site-grafana', layer: 'public-sites', label: 'grafana.completeautomate.com', subtitle: 'Monitoring', x: -100, z: 220, w: 220, h: 60, cat: 'site', desc: 'Grafana dashboards & alerts.', url: 'https://grafana.completeautomate.com' },
    { id: 'site-homepage', layer: 'public-sites', label: 'homepage.completeautomate.com', subtitle: 'Dashboard', x: 250, z: 220, w: 220, h: 60, cat: 'site', desc: 'Homepage service dashboard.', url: 'https://homepage.completeautomate.com' },
    { id: 'site-arch', layer: 'public-sites', label: 'arch.completeautomate.com', subtitle: 'Architecture Map', x: 600, z: 220, w: 220, h: 60, cat: 'site', desc: '3D system architecture viewer.', url: 'https://arch.completeautomate.com' },
    { id: 'site-ops', layer: 'public-sites', label: 'ops.completeautomate.com', subtitle: 'Ansible Semaphore', x: 950, z: 220, w: 220, h: 60, cat: 'site', desc: 'Ansible automation UI.', url: 'https://ops.completeautomate.com' },
    // Services
    { id: 'clio', layer: 'services', label: 'Clio', subtitle: 'DynamoDB ORM', x: -900, z: 170, w: 200, h: 60, cat: 'service', desc: 'Single-table DynamoDB abstraction layer.', url: 'https://wiki.completeautomate.com' },
    { id: 'pythia', layer: 'services', label: 'Pythia', subtitle: 'Lead Engine', x: -540, z: 170, w: 200, h: 60, cat: 'service', desc: 'AI lead scoring & enrichment engine.', url: 'https://wiki.completeautomate.com' },
    { id: 'angelos', layer: 'services', label: 'Angelos', subtitle: 'API Gateway', x: -180, z: 170, w: 200, h: 60, cat: 'service', desc: 'Contact form API & gateway.', url: 'https://messages.completeautomate.com' },
    { id: 'iris', layer: 'services', label: 'Iris', subtitle: 'Email Delivery', x: 180, z: 170, w: 200, h: 60, cat: 'service', desc: 'SMTP email delivery service.', url: 'https://wiki.completeautomate.com' },
    { id: 'orpheus', layer: 'services', label: 'Orpheus', subtitle: 'YouTube Mgmt', x: 540, z: 170, w: 200, h: 60, cat: 'service', desc: 'YouTube video management.', url: 'https://wiki.completeautomate.com' },
    { id: 'helios', layer: 'services', label: 'Helios', subtitle: 'Dashboard UI', x: -700, z: 105, w: 200, h: 60, cat: 'service', desc: 'Admin dashboard frontend.', url: 'https://admin.completeautomate.com' },
    { id: 'atlas', layer: 'services', label: 'Atlas', subtitle: 'File Storage', x: -350, z: 105, w: 200, h: 60, cat: 'service', desc: 'S3-compatible file storage API.', url: 'https://wiki.completeautomate.com' },
    { id: 'athena', layer: 'services', label: 'Athena', subtitle: 'Monitoring Bot', x: 0, z: 105, w: 200, h: 60, cat: 'service', desc: 'Telegram monitoring & alerts.', url: '' },
    { id: 'n8n', layer: 'services', label: 'N8N', subtitle: 'Workflow Automation', x: 350, z: 105, w: 200, h: 60, cat: 'service', desc: 'Workflow automation engine.', url: '' },
    { id: 'blog-watcher', layer: 'services', label: 'Blog Watcher', subtitle: 'RSS Monitor', x: 700, z: 105, w: 200, h: 60, cat: 'service', desc: 'RSS feed monitoring & content.', url: '' },
    // External
    { id: 'dynamodb', layer: 'external', label: 'DynamoDB', subtitle: 'AWS Database', x: -700, z: 30, w: 200, h: 60, cat: 'external', desc: 'Amazon DynamoDB database.', url: '' },
    { id: 's3', layer: 'external', label: 'S3', subtitle: 'AWS Storage', x: -250, z: 30, w: 200, h: 60, cat: 'external', desc: 'Amazon S3 media storage.', url: '' },
    { id: 'openrouter', layer: 'external', label: 'OpenRouter', subtitle: 'LLM API Gateway', x: 250, z: 30, w: 200, h: 60, cat: 'external', desc: 'LLM API gateway for AI calls.', url: '' },
    { id: 'zoho', layer: 'external', label: 'Zoho SMTP', subtitle: 'Email Outbound', x: 700, z: 30, w: 200, h: 60, cat: 'external', desc: 'Zoho SMTP for outbound email.', url: '' },
  ],
  connections: [
    { from: 'dns', to: 'site-main' }, { from: 'tunnel', to: 'site-main' },
    { from: 'dns', to: 'site-admin' }, { from: 'tunnel', to: 'site-admin' },
    { from: 'dns', to: 'site-grafana' }, { from: 'tunnel', to: 'site-grafana' },
    { from: 'dns', to: 'site-homepage' }, { from: 'tunnel', to: 'site-homepage' },
    { from: 'dns', to: 'site-arch' }, { from: 'tunnel', to: 'site-arch' },
    { from: 'dns', to: 'site-ops' }, { from: 'tunnel', to: 'site-ops' },
    { from: 'site-main', to: 'angelos' },
    { from: 'site-admin', to: 'helios' },
    { from: 'site-admin', to: 'pythia' },
    { from: 'site-grafana', to: 'clio' },
    { from: 'clio', to: 'dynamodb' },
    { from: 'pythia', to: 'openrouter' },
    { from: 'pythia', to: 's3' },
    { from: 'atlas', to: 's3' },
    { from: 'iris', to: 'zoho' },
    { from: 'angelos', to: 'iris' },
    { from: 'blog-watcher', to: 'atlas' },
    { from: 'athena', to: 'pythia' },
    { from: 'n8n', to: 'helios' },
  ],
  flows: {
    'site-main': {
      label: 'User visits completeautomate.com',
      hops: [
        { node: 'dns', duration: 200 },
        { arrow: ['dns', 'site-main'] as [string, string], node: 'site-main', duration: 200 },
        { arrow: ['site-main', 'angelos'] as [string, string], node: 'angelos', duration: 300 },
      ],
    },
    pythia: {
      label: 'AI Lead Enrichment',
      hops: [
        { node: 'pythia', duration: 300 },
        { arrow: ['pythia', 'openrouter'] as [string, string], node: 'openrouter', duration: 600 },
        { arrow: ['pythia', 's3'] as [string, string], node: 's3', duration: 400 },
      ],
    },
    angelos: {
      label: 'Contact Form → Email',
      hops: [
        { node: 'angelos', duration: 200 },
        { arrow: ['angelos', 'iris'] as [string, string], node: 'iris', duration: 300 },
        { arrow: ['iris', 'zoho'] as [string, string], node: 'zoho', duration: 300 },
      ],
    },
    clio: {
      label: 'DynamoDB Query',
      hops: [
        { node: 'clio', duration: 200 },
        { arrow: ['clio', 'dynamodb'] as [string, string], node: 'dynamodb', duration: 300 },
      ],
    },
  },
};

export const cluster: EnvironmentDef = {
  label: '🔷 k3s Cluster',
  cameraPos: [0, -800, 300],
  cameraTarget: [0, 0, 155],
  layers: [
    { id: 'infra', label: '🔧 Infrastructure', z: 300, w: 2400, h: 140 },
    { id: 'observability', label: '📊 Observability', z: 230, w: 2400, h: 110 },
    { id: 'microservices', label: '⚙️ Microservices', z: 160, w: 2400, h: 140 },
    { id: 'apps', label: '🌐 Apps', z: 80, w: 2400, h: 130 },
    { id: 'cicd', label: '🔄 CI / Backups', z: 10, w: 2400, h: 110 },
  ],
  nodes: [
    // Infrastructure
    { id: 'traefik', layer: 'infra', label: 'Traefik', subtitle: 'Ingress Controller', x: -900, z: 300, w: 200, h: 65, cat: 'cluster', desc: 'Kubernetes ingress controller.', url: '' },
    { id: 'metallb', layer: 'infra', label: 'MetalLB', subtitle: 'Load Balancer', x: -550, z: 300, w: 200, h: 65, cat: 'cluster', desc: 'Bare-metal load balancer.', url: '' },
    { id: 'authelia', layer: 'infra', label: 'Authelia', subtitle: 'SSO Auth', x: -200, z: 300, w: 200, h: 65, cat: 'cluster', desc: 'Single sign-on authentication.', url: 'https://auth.completeautomate.com' },
    { id: 'argocd', layer: 'infra', label: 'ArgoCD', subtitle: 'GitOps', x: 150, z: 300, w: 200, h: 65, cat: 'cluster', desc: 'GitOps deployment automation.', url: 'https://argocd.completeautomate.com' },
    { id: 'cert-manager', layer: 'infra', label: 'cert-manager', subtitle: 'SSL Certificates', x: 500, z: 300, w: 200, h: 65, cat: 'cluster', desc: 'Automated SSL certificate management.', url: '' },
    { id: 'eso', layer: 'infra', label: 'External Secrets', subtitle: 'Secrets Mgmt', x: 850, z: 300, w: 200, h: 65, cat: 'cluster', desc: 'Syncs AWS secrets to Kubernetes.', url: '' },
    { id: 'nfs', layer: 'infra', label: 'NFS Provisioner', subtitle: 'Persistent Storage', x: 1150, z: 300, w: 200, h: 65, cat: 'cluster', desc: 'NFS-based persistent volume provisioner.', url: '' },
    // Observability
    { id: 'prometheus', layer: 'observability', label: 'Prometheus', subtitle: 'Metrics', x: -400, z: 230, w: 200, h: 55, cat: 'cluster', desc: 'Metrics collection & alerting.', url: '' },
    { id: 'grafana', layer: 'observability', label: 'Grafana', subtitle: 'Dashboards', x: 0, z: 230, w: 200, h: 55, cat: 'cluster', desc: 'Monitoring dashboards & visualization.', url: 'https://grafana.completeautomate.com' },
    { id: 'loki', layer: 'observability', label: 'Loki', subtitle: 'Log Aggregation', x: 400, z: 230, w: 200, h: 55, cat: 'cluster', desc: 'Centralized log aggregation.', url: '' },
    // Microservices
    { id: 'clio', layer: 'microservices', label: 'Clio', subtitle: 'DynamoDB ORM', x: -800, z: 160, w: 200, h: 60, cat: 'service', desc: 'Single-table DynamoDB abstraction layer.', url: 'https://wiki.completeautomate.com' },
    { id: 'pythia', layer: 'microservices', label: 'Pythia', subtitle: 'Lead Engine', x: -480, z: 160, w: 200, h: 60, cat: 'service', desc: 'AI lead scoring & enrichment engine.', url: 'https://wiki.completeautomate.com' },
    { id: 'angelos', layer: 'microservices', label: 'Angelos', subtitle: 'API Gateway', x: -160, z: 160, w: 200, h: 60, cat: 'service', desc: 'Contact form API & gateway.', url: 'https://messages.completeautomate.com' },
    { id: 'iris', layer: 'microservices', label: 'Iris', subtitle: 'Email Delivery', x: 160, z: 160, w: 200, h: 60, cat: 'service', desc: 'SMTP email delivery service.', url: 'https://wiki.completeautomate.com' },
    { id: 'orpheus', layer: 'microservices', label: 'Orpheus', subtitle: 'YouTube Mgmt', x: 480, z: 160, w: 200, h: 60, cat: 'service', desc: 'YouTube video management.', url: 'https://wiki.completeautomate.com' },
    { id: 'helios', layer: 'microservices', label: 'Helios', subtitle: 'Dashboard UI', x: 800, z: 160, w: 200, h: 60, cat: 'service', desc: 'Admin dashboard frontend.', url: 'https://admin.completeautomate.com' },
    { id: 'atlas', layer: 'microservices', label: 'Atlas', subtitle: 'File Storage', x: -300, z: 115, w: 200, h: 60, cat: 'service', desc: 'S3-compatible file storage API.', url: 'https://wiki.completeautomate.com' },
    { id: 'athena', layer: 'microservices', label: 'Athena', subtitle: 'Monitoring Bot', x: 300, z: 115, w: 200, h: 60, cat: 'service', desc: 'Telegram monitoring & alerts.', url: '' },
    // Apps
    { id: 'app-homepage', layer: 'apps', label: 'Homepage', subtitle: 'Dashboard', x: -900, z: 80, w: 200, h: 60, cat: 'site', desc: 'Service dashboard homepage.', url: 'https://homepage.completeautomate.com' },
    { id: 'app-arch', layer: 'apps', label: 'Architecture', subtitle: '3D Canvas', x: -600, z: 80, w: 200, h: 60, cat: 'site', desc: 'System architecture viewer.', url: 'https://arch.completeautomate.com' },
    { id: 'app-semaphore', layer: 'apps', label: 'Semaphore', subtitle: 'Ansible UI', x: -300, z: 80, w: 200, h: 60, cat: 'site', desc: 'Ansible automation management.', url: 'https://ops.completeautomate.com' },
    { id: 'app-wiki', layer: 'apps', label: 'Wiki', subtitle: 'Documentation', x: 0, z: 80, w: 200, h: 60, cat: 'site', desc: 'Internal documentation site.', url: 'https://wiki.completeautomate.com' },
    { id: 'app-n8n', layer: 'apps', label: 'N8N', subtitle: 'Workflow Engine', x: 300, z: 80, w: 200, h: 60, cat: 'site', desc: 'Workflow automation engine.', url: '' },
    { id: 'app-kuma', layer: 'apps', label: 'Uptime Kuma', subtitle: 'Health Checks', x: 600, z: 80, w: 200, h: 60, cat: 'site', desc: 'Service uptime monitoring.', url: '' },
    { id: 'app-pihole', layer: 'apps', label: 'Pi-hole', subtitle: 'DNS Filter', x: -500, z: 35, w: 200, h: 60, cat: 'site', desc: 'Network-wide ad blocking & DNS.', url: '' },
    { id: 'app-vaultwarden', layer: 'apps', label: 'Vaultwarden', subtitle: 'Password Mgmt', x: -200, z: 35, w: 200, h: 60, cat: 'site', desc: 'Self-hosted password manager.', url: '' },
    { id: 'app-netalertx', layer: 'apps', label: 'NetAlertX', subtitle: 'Network Monitor', x: 200, z: 35, w: 200, h: 60, cat: 'site', desc: 'Network device discovery & monitoring.', url: '' },
    // CI/Backups
    { id: 'gh-actions', layer: 'cicd', label: 'GitHub Actions', subtitle: 'CI/CD', x: -250, z: 10, w: 220, h: 60, cat: 'external', desc: 'Continuous integration and deployment.', url: '' },
    { id: 'backups', layer: 'cicd', label: 'Backups', subtitle: 'Automated', x: 250, z: 10, w: 220, h: 60, cat: 'external', desc: 'Automated cluster & data backups to S3.', url: '' },
  ],
  connections: [
    { from: 'metallb', to: 'traefik' },
    { from: 'traefik', to: 'authelia' },
    { from: 'argocd', to: 'traefik' },
    { from: 'cert-manager', to: 'traefik' },
    { from: 'eso', to: 'authelia' },
    { from: 'traefik', to: 'prometheus' },
    { from: 'traefik', to: 'loki' },
    { from: 'prometheus', to: 'grafana' },
    { from: 'loki', to: 'grafana' },
    { from: 'traefik', to: 'clio' }, { from: 'traefik', to: 'pythia' },
    { from: 'traefik', to: 'angelos' }, { from: 'traefik', to: 'iris' },
    { from: 'traefik', to: 'orpheus' }, { from: 'traefik', to: 'helios' },
    { from: 'traefik', to: 'atlas' }, { from: 'traefik', to: 'athena' },
    { from: 'traefik', to: 'app-homepage' }, { from: 'traefik', to: 'app-arch' },
    { from: 'traefik', to: 'app-semaphore' }, { from: 'traefik', to: 'app-wiki' },
    { from: 'traefik', to: 'app-n8n' }, { from: 'traefik', to: 'app-kuma' },
    { from: 'traefik', to: 'app-pihole' }, { from: 'traefik', to: 'app-vaultwarden' },
    { from: 'traefik', to: 'app-netalertx' },
    { from: 'gh-actions', to: 'argocd' },
    { from: 'backups', to: 'nfs' },
  ],
  flows: {},
};
